# Generated by Django 4.0.4 on 2022-05-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='Products',
        ),
    ]
