# Generated by Django 4.0.4 on 2022-06-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_products_size_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['category'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
