# Generated by Django 4.0.4 on 2022-05-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_laptop_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/products/None/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
