# Generated by Django 4.0.4 on 2022-05-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(default=1, upload_to='image/catigories/%Y/%m/%d', verbose_name='Главное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
