# Generated by Django 4.0.4 on 2022-05-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_products_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ImageField(height_field='600', upload_to='image/products/%Y/%m/%d', verbose_name='Главное изображение', width_field='600'),
        ),
    ]
