# Generated by Django 4.0.4 on 2022-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_products_main_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catigories',
            new_name='Categories',
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
