# Generated by Django 4.0.4 on 2022-05-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_catigories_categories_products_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='name_model',
        ),
        migrations.RemoveField(
            model_name='products',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Производитель'),
        ),
    ]
