# Generated by Django 4.0.4 on 2022-06-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
