# Generated by Django 4.0.4 on 2022-06-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_alter_products_size_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=55, verbose_name='Имя клиента')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('comment', models.TextField(db_index=True, max_length=255, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.products', verbose_name='Название продукта')),
            ],
        ),
    ]
