# Generated by Django 4.0.4 on 2022-06-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=254, verbose_name='Email, клиента'),
            preserve_default=False,
        ),
    ]
