# Generated by Django 4.0.4 on 2022-06-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0002_reviews_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
